version: "3.8"
services:
  app:
    privileged: true
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./videos:/app/videos
    devices:
      - /dev/video0:/dev/video0
